---
- name: Prepare Packages
  hosts: local
  vars_files:
    - "roles/dpm_main/vars/main.yml"
  roles:
    - common

- name: Prepare Infrasctructure
  hosts: dpm_main
  become: true
  roles:
    - dpm_main

- name: Prepare DB Infrasctructure
  hosts: dpm_db
  become: true
  roles:
    - dpm_db
