---
wf:
  vers: 10.0.0
  srvc:
    - port: 8080
      env: 'DEV1'
    - port: 8090
      env: 'DEV2'
    - port: 9090
      env: 'DEV3'
ngnx:
  vers: 1.12.1
jdk:
  vers: 8u144
  url: "none"

wf_url: "http://download.jboss.org/wildfly/{{ wf.vers }}.Final/wildfly-{{ wf.vers }}.Final.tar.gz"
ngnx_irl: "https://nginx.org/packages/rhel/7/x86_64/RPMS/nginx-{{ ngnx.vers }}-1.el7.ngx.x86_64.rpm"
