---
- name: Create temp download dir
  file:
    name: /tmp/dpm_pkg
    state: directory
- name: Download Java
  get_url:
    url: "{{ jdk_url }}"
    headers: 'Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
    dest: "/tmp/dpm_pkg/jdk-{{ jdk.vers }}-linux-x64.rpm"
    timeout: 120
- name: Download WF and Nginx
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/dpm_pkg/{{ item.name }}"
    timeout: 120
  with_items:
    - { url: "{{ ngnx_url }}", name: "nginx-{{ ngnx.vers }}-1.el7.ngx.x86_64.rpm" }
    - { url: "{{ wf_url }}", name: "wildfly-{{ wf.vers }}.Final.tar.gz" }
